//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Strings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More.
        /// </summary>
        internal static string carouselBTN {
            get {
                return ResourceManager.GetString("carouselBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROVIDING.
        /// </summary>
        internal static string carouselH {
            get {
                return ResourceManager.GetString("carouselH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string carouselNext {
            get {
                return ResourceManager.GetString("carouselNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIGH QUALITY PRODUCTS AND SERVICES.
        /// </summary>
        internal static string carouselP {
            get {
                return ResourceManager.GetString("carouselP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string carouselPrevious {
            get {
                return ResourceManager.GetString("carouselPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address: .
        /// </summary>
        internal static string contactAddress {
            get {
                return ResourceManager.GetString("contactAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax:.
        /// </summary>
        internal static string contactFax {
            get {
                return ResourceManager.GetString("contactFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave us a message.
        /// </summary>
        internal static string contactMessage {
            get {
                return ResourceManager.GetString("contactMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone: .
        /// </summary>
        internal static string contactPhone {
            get {
                return ResourceManager.GetString("contactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string contactSubmit {
            get {
                return ResourceManager.GetString("contactSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        internal static string header1 {
            get {
                return ResourceManager.GetString("header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I.
        /// </summary>
        internal static string header2 {
            get {
                return ResourceManager.GetString("header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        internal static string header3 {
            get {
                return ResourceManager.GetString("header3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT US.
        /// </summary>
        internal static string menuAboutUs {
            get {
                return ResourceManager.GetString("menuAboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTING.
        /// </summary>
        internal static string menuConsulting {
            get {
                return ResourceManager.GetString("menuConsulting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT.
        /// </summary>
        internal static string menuContact {
            get {
                return ResourceManager.GetString("menuContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME.
        /// </summary>
        internal static string menuHome {
            get {
                return ResourceManager.GetString("menuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVICES.
        /// </summary>
        internal static string menuServices {
            get {
                return ResourceManager.GetString("menuServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brochem’s owners are chemical engineers. Our team consists of highly experienced individuals with successful track records acquired in market leading multinational companies. We have more than two decades of experience in the packaging industry, in international trade and distribution of pharmaceuticals. We supply high quality products and solution oriented services to our customers in Turkey and abroad.
        ///
        ///Our intimate knowledge of polymer chemistry and extensive experience in the global flexible packaging [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string p1AboutUs {
            get {
                return ResourceManager.GetString("p1AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging industry Food Safety, Hygiene Training , AIB and BRC / IoP Food Safety For installation Systems.
        /// </summary>
        internal static string partEducation1 {
            get {
                return ResourceManager.GetString("partEducation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction and optimization of quality control processes.
        /// </summary>
        internal static string partEducation10 {
            get {
                return ResourceManager.GetString("partEducation10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product R&amp;D.
        /// </summary>
        internal static string partEducation11 {
            get {
                return ResourceManager.GetString("partEducation11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product development and formulations of plastic films (BOPP, CPP, PET, Coated Films).
        /// </summary>
        internal static string partEducation12 {
            get {
                return ResourceManager.GetString("partEducation12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TS EN ISO 9001 Quality Management System.
        /// </summary>
        internal static string partEducation2 {
            get {
                return ResourceManager.GetString("partEducation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TS EN ISO 14001 Environment Management System.
        /// </summary>
        internal static string partEducation3 {
            get {
                return ResourceManager.GetString("partEducation3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TS 18001 Occupational Hhealth and Safety Management System.
        /// </summary>
        internal static string partEducation4 {
            get {
                return ResourceManager.GetString("partEducation4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TS EN ISO 22000 Food Safety Management System.
        /// </summary>
        internal static string partEducation5 {
            get {
                return ResourceManager.GetString("partEducation5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastics Industry and Packaging Materials Production Systems..
        /// </summary>
        internal static string partEducation6 {
            get {
                return ResourceManager.GetString("partEducation6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BroChem’s owners look back on a 25 years history of chemically engineering polymers, plastics and packaging material and their manifold applications and production techniques..
        /// </summary>
        internal static string partEducation7 {
            get {
                return ResourceManager.GetString("partEducation7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer of polymer specific state-of-the-art Know-how.
        /// </summary>
        internal static string partEducation8 {
            get {
                return ResourceManager.GetString("partEducation8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improvement of production processes.
        /// </summary>
        internal static string partEducation9 {
            get {
                return ResourceManager.GetString("partEducation9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string partHeaderAboutUs {
            get {
                return ResourceManager.GetString("partHeaderAboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string partHeaderContactUs {
            get {
                return ResourceManager.GetString("partHeaderContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT INFORMATION.
        /// </summary>
        internal static string partHeaderContactUsDetail {
            get {
                return ResourceManager.GetString("partHeaderContactUsDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTING &amp; SERVICES.
        /// </summary>
        internal static string partHeaderEducation {
            get {
                return ResourceManager.GetString("partHeaderEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CORE BUSSINESSES.
        /// </summary>
        internal static string partHeaderProducts {
            get {
                return ResourceManager.GetString("partHeaderProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string placeholderMessage {
            get {
                return ResourceManager.GetString("placeholderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string placeholderName {
            get {
                return ResourceManager.GetString("placeholderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        internal static string placeholderPhone {
            get {
                return ResourceManager.GetString("placeholderPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International Trade.
        /// </summary>
        internal static string productInternationalTrade {
            get {
                return ResourceManager.GetString("productInternationalTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BroChem is internationally trading raw materials and food products. We trade foodstuff mostly between Turkey and the Balkans. .
        /// </summary>
        internal static string productInternationalTradeDetail {
            get {
                return ResourceManager.GetString("productInternationalTradeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We trade foodstuff mostly between Turkey and the Balkans..
        /// </summary>
        internal static string productInternationalTradeDetail2 {
            get {
                return ResourceManager.GetString("productInternationalTradeDetail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are your most reliable source for a broad range of high quality and cost efficient chemical components and raw materials used in the production of plastics such as polymers, petrochemicals and ancillary products..
        /// </summary>
        internal static string productInternationalTradeDetail3 {
            get {
                return ResourceManager.GetString("productInternationalTradeDetail3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmaceutical Sector.
        /// </summary>
        internal static string productPharmaceuticalSector {
            get {
                return ResourceManager.GetString("productPharmaceuticalSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BroChem is a distributor of several reputable European drug companies for medicinal products for human and animal use alike for 15 countries over EMEA and Central Asia. We provide safe, cost efficient and high quality pharmaceuticals to our distribution network of pharmacies and wholesalers. Our corporate structure and swift decision making process allows the successful participation in state tenders as well as a short reaction time to serve as your procurement partner in emergency exports. We assure a time [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string productPharmaceuticalSectorDetail {
            get {
                return ResourceManager.GetString("productPharmaceuticalSectorDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastics Sector.
        /// </summary>
        internal static string productPlasticsSector {
            get {
                return ResourceManager.GetString("productPlasticsSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BroChem supports you in all aspects related to flexible packaging and food packaging. Our activities range from reliable raw material supply to R&amp;D, contract packaging or simply providing you with the best assistance aimed at improving your own production processes. In addition, we share technical and commercial expertise with our customers the main emphasis being continued improvement of process design, quality control, and regulatory compliance while optimizing costs structures..
        /// </summary>
        internal static string productPlasticsSectorDetail {
            get {
                return ResourceManager.GetString("productPlasticsSectorDetail", resourceCulture);
            }
        }
    }
}
